name: prochat-server-dev

services:
  postgres:
    image: postgres:alpine
    container_name: prochat-database-dev
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - prochat-pg:/var/lib/postgresql/data

volumes:
  prochat-pg: